version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm" 
    directory: "/apps/_root" 
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm" 
    directory: "/apps/earn" 
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm" 
    directory: "/apps/swap"
    schedule:
      interval: "weekly"

      
