services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - root
      - swap
      - earn
    networks:
      - app-network
    restart: unless-stopped

  root:
    image: ghcr.io/hbulldozer/dozer/root-app-testnet:latest
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=9000
      - HOSTNAME=0.0.0.0
      - ROOT_URL=https://self-testnet.dozer.finance
      - SWAP_URL=https://self-testnet.dozer.finance
      - EARN_URL=https://self-testnet.dozer.finance
    volumes:
      - root_cache:/app/apps/_root/.next/cache
    networks:
      - app-network
    restart: unless-stopped

  swap:
    image: ghcr.io/hbulldozer/dozer/swap-app-testnet:latest
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=9001
      - HOSTNAME=0.0.0.0
    volumes:
      - swap_cache:/app/apps/swap/.next/cache
    networks:
      - app-network
    restart: unless-stopped

  earn:
    image: ghcr.io/hbulldozer/dozer/earn-app-testnet:latest
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=9002
      - HOSTNAME=0.0.0.0
    volumes:
      - earn_cache:/app/apps/earn/.next/cache
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  root_cache:
  swap_cache:
  earn_cache: