name: GCP Testnet Deployment

on:
  push:
    branches: [ gcp-testnet ]
  pull_request:
    branches: [ gcp-testnet ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      root_image: ${{ steps.build-root.outputs.imageid }}
      swap_image: ${{ steps.build-swap.outputs.imageid }}
      earn_image: ${{ steps.build-earn.outputs.imageid }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "${{ secrets.GCP_ENV_FILE }}" > .env
          # Debug: Print first line of env file (excluding sensitive data)
          head -n 1 .env | sed 's/=.*/=***/'

      - name: Set up Docker Buildx
        uses: docker/build-push-action@v3

      - name: Google Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
          
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for GCP
        run: |
          gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev
          
      - name: Cache for Turbo
        uses: rharkor/caching-for-turbo@v1.5

      - name: Build and push root image
        id: build-root
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/dozer/root-app:${{ github.sha }}
          target: root-runner
          secret-files: |
            env=.env

      - name: Build and push swap image
        id: build-swap
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/dozer/swap-app:${{ github.sha }}
          target: swap-runner
          secret-files: |
            env=.env

      - name: Build and push earn image
        id: build-earn
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/dozer/earn-app:${{ github.sha }}
          target: earn-runner
          secret-files: |
            env=.env

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Google Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
          
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Create ENV variables file and debug
        run: |
          echo "${{ secrets.GCP_ENV_FILE }}" > .env
          # Convert .env file to comma-separated format for Cloud Run
          ENV_VARS=$(cat .env | grep -v '^#' | grep '=' | sed 's/\r//g' | sed 's/^//' | paste -sd,)
          # Debug: Print number of env vars (without values)
          echo "Number of env vars: $(echo $ENV_VARS | tr ',' '\n' | wc -l)"
          # Debug: Print env var names (without values)
          echo "Env var names:"
          echo $ENV_VARS | tr ',' '\n' | cut -d'=' -f1

      # Deploy swap app
      - name: Deploy swap app to Cloud Run
        id: deploy-swap
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: swap-app
          image: ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/dozer/swap-app:${{ github.sha }}
          region: ${{ secrets.GCP_REGION }}
          env_vars: |
            ${{ env.ENV_VARS }}
            NODE_ENV=production
            HOSTNAME=0.0.0.0
          flags: --allow-unauthenticated

      # Deploy earn app
      - name: Deploy earn app to Cloud Run
        id: deploy-earn
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: earn-app
          image: ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/dozer/earn-app:${{ github.sha }}
          region: ${{ secrets.GCP_REGION }}
          env_vars: |
            ${{ env.ENV_VARS }}
            NODE_ENV=production
            HOSTNAME=0.0.0.0
          flags: --allow-unauthenticated

      # Deploy root app with debug output
      - name: Deploy root app to Cloud Run
        id: deploy-root
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: root-app
          image: ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/dozer/root-app:${{ github.sha }}
          region: ${{ secrets.GCP_REGION }}
          env_vars: |
            ${{ env.ENV_VARS }}
            NODE_ENV=production
            HOSTNAME=0.0.0.0
            ROOT_URL=https://gcp-testnet.dozer.finance
            SWAP_URL=${{ steps.deploy-swap.outputs.url }}
            EARN_URL=${{ steps.deploy-earn.outputs.url }}
          flags: --allow-unauthenticated

      - name: Debug Environment URLs
        run: |
          echo "Root app URL: ${{ steps.deploy-root.outputs.url }}"
          echo "Swap app URL: ${{ steps.deploy-swap.outputs.url }}"
          echo "Earn app URL: ${{ steps.deploy-earn.outputs.url }}"
          
          # Verify the services are responding
          curl -I ${{ steps.deploy-root.outputs.url }}
          curl -I ${{ steps.deploy-swap.outputs.url }}
          curl -I ${{ steps.deploy-earn.outputs.url }}